version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: markdown-editor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: markdown_editor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Optionnel: Interface web pour PostgreSQL
  adminer:
    image: adminer:latest
    container_name: markdown-editor-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
